# Add application configuration variables here, as shown below.
SENDGRID_USERNAME: app45404750@heroku.com
SENDGRID_PASSWORD: nszwuhhf1798
S3_KEY_ID: XXXXXXXXXXXXXXXXXXXXXXX
S3_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXX
GOOGLE_KEY: ZZZZZZZZZZZZZZZZZZZZ
GOOGLE_SECRET: ZZZZZZZZZZZZZZZZZZZZ
FACEBOOK_APP_ID: WWWWWWWWWWWWWWWWWWWWW
FACEBOOK_SECRET: WWWWWWWWWWWWWWWWWWWWW